{% set version = "0.8.1" %}

package:
  name: ansible-bender
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/a/ansible-bender/ansible-bender-{{ version }}.tar.gz
  sha256: fd334e5d8b2785075443f9b4a5e0558c1551a62dddef35e9e82a83eb66802a61

build:
  number: 1
  noarch: python
  entry_points:
    - ansible-bender = ansible_bender.cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools_scm
    - setuptools_scm_git_archive
  run:
    - python >={{ python_min }}
    - jsonschema
    - pyyaml
    - tabulate
    - ansible

test:
  imports:
    - ansible_bender
  commands:
    - pip check
    - ansible-bender --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/ansible-community/ansible-bender
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A tool which builds container images using Ansible playbooks
  doc_url: https://ansible-community.github.io/ansible-bender/build/html/index.html
  dev_url: https://github.com/ansible-community/ansible-bender

extra:
  recipe-maintainers:
    - lsetiawan
